name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install brew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install pop-cli
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install r0gue-io/pop-cli/pop

      - name: Install dependencies
        run: pop install

      - name: Lint the code
        run: cargo +nightly fmt --check

      - name: Build contract
        run: pop build

      - name: Run unit tests
        run: pop test

      - name: Run end-to-end tests
        run: pop test --e2e -y
